permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

# 作者信息
author: 
  name: Kute Bai
  email: kutekute00@gmail.com
  link: http://kute.github.io
  github: http://github.com/kute

# 站点信息
title: 库特的博客
description: Tiny blog for everything
url: http://painterlin.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/author.jpg
favicon: /public/img/pylogo.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: painterlin.com

# disqus 设置
disqus:
  shortname: painterlin

# 主题设置，自动激活某个标签
active: Linux

# 首页除了最新文章外显示分类
cates:
  - Python
  - Java
  - Scala
  - Linux

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档